[package]
name = "wg-mtu-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
chrono = "0.4.40"
clap = "2.34.0"
csv = "1.3.1"
plotters = "0.3.7"
thiserror = "2.0.11"
