name: Rust Musl Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Create symbolic link for musl-g++
        run: sudo ln -s /usr/bin/g++ /usr/bin/musl-g++

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libfreetype6-dev libfontconfig1-dev

      - name: Set environment variables for pkg-config
        run: |
          echo 'PKG_CONFIG_ALLOW_CROSS=1' >> $GITHUB_ENV
          echo 'PKG_CONFIG_PATH=/usr/x86_64-linux-musl/lib/pkgconfig' >> $GITHUB_ENV
          echo 'PKG_CONFIG_SYSROOT_DIR=/usr/x86_64-linux-musl' >> $GITHUB_ENV

      - name: Build with musl
        run: cargo build --target x86_64-unknown-linux-musl --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wg-mtu-finder
          path: target/x86_64-unknown-linux-musl/release/wg-mtu-finder
