name: Rust Musl Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build with musl
        run: cargo build --target x86_64-unknown-linux-musl --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rust-musl-executable
          path: target/x86_64-unknown-linux-musl/release/wg-mtu-finder
